version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/DailyStatus
permissions:
 - object: /
   owner: ubuntu
   group: ubuntu
hooks:
 BeforeInstall:
   - location: config/BeforeInstall.sh
     timeout: 100
     runas: ubuntu
 AfterInstall:
   - location: config/AfterInstall.sh
     timeout: 100
     runas: ubuntu
