# Generated by Django 3.2 on 2023-08-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
    ]
