# Generated by Django 3.2 on 2023-08-14 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0002_remove_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
