# Generated by Django 3.2 on 2023-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0004_stream_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
