# Generated by Django 3.2 on 2023-08-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0006_userprofile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_user', to='ds_app.userprofile'),
        ),
    ]
