# Generated by Django 3.2 on 2023-08-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0008_sendmailstrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailsTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_mail_sent', models.BooleanField(default=False)),
                ('mail_sent_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='SendMailsTrack',
        ),
    ]
